version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4378:4378"
    volumes:
      - ./src:/app/src
      - ./angular.json:/app/angular.json
      - ./tsconfig.json:/app/tsconfig.json
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "start"]
